language: python
os: linux
dist: bionic
services:
  - xvfb
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle isort
script:
  - isort . --diff
  - pycodestyle tests/
  - QT_QPA_PLATFORM=offscreen xvfb-run -a --server-args="-screen 0 1024x768x24" nosetests
  - QT_QPA_PLATFORM=xvfb xvfb-run -a --server-args="-screen 0 1024x768x24" nosetests
notifications:
  irc: false
  email: false
