language: python
os: linux
dist: bionic
services:
  - xvfb
python:
  - "3.9"
install:
  - pip install PyQt5 pycodestyle isort
script:
  - isort . --diff
  - pycodestyle tests/
  - xvfb-run nosetests
notifications:
  irc: false
  email: false
