language: python
sudo: required
dist: trusty
python:
  - "3.9"
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install PyQt5 pycodestyle
script:
 - pycodestyle tests/
 - nosetests
notifications:
  irc: false
  email: false
