os: Visual Studio 2015
version: '{branch}-b{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "win32"
      PyQT: "http://download.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5/PyQt5-5.5-gpl-Py3.4-Qt5.5.0-x32.exe"
init:
  - ps: "ls -Name \"C:/\""
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - REG ADD HKCU\Software\Python\PythonCore\3.4\InstallPath /f /ve /t REG_SZ /d %PYTHON%
  - git submodule update --init --recursive
  - ps: Start-FileDownload $env:PyQT -FileName $env:temp/pyqt5_install.exe
  - ps: "& $env:temp/pyqt5_install.exe /S"
  - ps: "Wait-Process -Name pyqt5_install -Timeout 600"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -c \"import PyQt5\""
  - "pip --version"
  - "pip install requests pyinstaller"

build_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - "pyinstaller --icon=resources/images/logo.ico treenote.py"
  - ps: "cp -r resources dist/"
  - cd dist
  - ps: "& 7z a -r treenote.zip ."

test: off

artifacts:
  - path: dist/treenote.zip
